from django.conf.urls import url
from .views import *

url_patterns = [
    url(r'^home/', homepage, name='homepage'),
    url(r'^login/', login, name='login_page'),
    url(r'^submit/(\d+)/', submit_problem, name='submit_problem'),
    url(r'^problem/', problem_home, name='problem_home'),
    url(r'^submissions/$', problem_submissions, name='problem_submission'),
    url(r'^submissions/(\d+)/', problem_submission_info, name='problem_submission_info'),
    url(r'^problems/$', problem, name='problem_problem'),
    url(r'^problems/(\d+)/', problem_instance, name='problem_problem_instance'),
    url(r'^categories/$', problem_category, name='problem_category'),
    url(r'^categories/(\d+)/$', problem_category_instance, name='problem_category_instance'),
    url(r'^categories/(\d+)/directories/', problem_category_dir, name='problem_category_dir'),
    url(r'^meta-problems/$', problem_meta, name='problem_meta'),
    url(r'^meta-problems/create/', problem_meta_create, name='problem_meta_create'),
    url(r'^meta-problems/(\d+)/$', problem_meta_instance, name='problem_meta_instance'),
    url(r'^meta-problems/(\d+)/descriptions/$', problem_meta_description, name='problem_meta_description'),
    url(r'^meta-problems/(\d+)/descriptions/create/', problem_meta_description_create,
        name='problem_meta_description_create'),
    url(r'^meta-problems/(\d+)/descriptions/(\d+)/', problem_meta_description_instance,
        name='problem_meta_description_instance'),
    url(r'^meta-problems/(\d+)/samples/$', problem_meta_sample, name='problem_meta_sample'),
    url(r'^meta-problems/(\d+)/samples/create/', problem_meta_sample_create,
        name='problem_meta_sample_create'),
    url(r'^meta-problems/(\d+)/samples/(\d+)/', problem_meta_sample_instance,
        name='problem_meta_sample_instance'),
    url(r'^meta-problems/(\d+)/test-data/$', problem_meta_test, name='problem_meta_test'),
    url(r'^meta-problems/(\d+)/test-data/create/', problem_meta_test_create,
        name='problem_meta_test_create'),
    url(r'^meta-problems/(\d+)/test-data/(\d+)/', problem_meta_test_instance,
        name='problem_meta_test_instance'),
    url(r'^meta-problems/(\d+)/problems/$', problem_meta_problem, name='problem_meta_problem'),
    url(r'^meta-problems/(\d+)/problems/create/', problem_meta_problem_create,
        name='problem_meta_problem_create'),
    url(r'^meta-problems/(\d+)/problems/(\d+)/$', problem_meta_problem_instance,
        name='problem_meta_problem_instance'),
    url(r'^meta-problems/(\d+)/problems/(\d+)/limits/$', problem_meta_problem_limits,
        name='problem_meta_problem_limits'),
    url(r'^meta-problems/(\d+)/problems/(\d+)/limits/create/', problem_meta_problem_limits_create,
        name='problem_meta_problem_limits_create'),
    url(r'^meta-problems/(\d+)/problems/(\d+)/limits/(\d+)/', problem_meta_problem_limits_instance,
        name='problem_meta_problem_limits_instance'),
    url(r'^meta-problems/(\d+)/problems/(\d+)/special-judge/$', problem_meta_problem_spj,
        name='problem_meta_problem_spj'),
    url(r'^meta-problems/(\d+)/problems/(\d+)/special-judge/create/', problem_meta_problem_spj_create,
        name='problem_meta_problem_spj_create'),
    url(r'^meta-problems/(\d+)/problems/(\d+)/special-judge/(\d+)/', problem_meta_problem_spj_instance,
        name='problem_meta_problem_spj_instance'),
    url(r'^meta-problems/(\d+)/problems/(\d+)/invalid-words/$', problem_meta_problem_iw,
        name='problem_meta_problem_iw'),
    url(r'^meta-problems/(\d+)/problems/(\d+)/invalid-words/create/', problem_meta_problem_iw_create,
        name='problem_meta_problem_iw_create'),
    url(r'^meta-problems/(\d+)/problems/(\d+)/invalid-words/(\d+)/', problem_meta_problem_iw_instance,
        name='problem_meta_problem_iw_instance'),
    url(r'^meta-problems/(\d+)/problems/(\d+)/test-data/$', problem_meta_problem_test,
        name='problem_meta_problem_test'),
    url(r'^meta-problems/(\d+)/problems/(\d+)/test-date/create/', problem_meta_problem_test_create,
        name='problem_meta_problem_test_create'),
    url(r'^meta-problems/(\d+)/problems/(\d+)/test-data/(\d+)/', problem_meta_problem_test_instance,
        name='problem_meta_problem_test_instance'),
    url(r'^personal/info/', personal_info, name='personal-info-page'),
    url(r'^personal/edit/', personal_edit, name='personal-edit-page'),
    url(r'^personal/password/', personal_password, name='personal-password-page'),
    url(r'^clients/$', client_clients, name='client_clients'),
    url(r'^clients/create/', client_create, name='client_create'),
    url(r'^clients/(\d+)/$', client_instance, name='client_instance'),
    url(r'^clients/(\d+)/categories/$', client_categories, name='client_categories'),
    url(r'^clients/(\d+)/categories/create', client_categories_create, name='client_categories_create'),
    url(r'^clients/(\d+)/categories/(\d+)/', client_category_instance, name='client_category_instance'),
    url(r'^client-users/$', client_users, name='client_users'),
    url(r'^client-users/create/', client_user_create, name='client_user_create'),
    url(r'^client-users/instance/(\S+)/', client_user_instance, name='client_user_instance'),
    url(r'^users/$', users, name='users'),
    url(r'^users/create', user_create, name='user_create'),
    url(r'^users/instance/(\S+)/', user_instance, name='user_instance'),
]
