# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20170305_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eduadmin',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='eduadmin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orgadmin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='siteadmin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.AddField(
            model_name='personal',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='EduAdmin',
        ),
        migrations.DeleteModel(
            name='OrgAdmin',
        ),
        migrations.DeleteModel(
            name='SiteAdmin',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
