# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_auto_20170305_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduadmin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edu_admin_info', to='rest_api.Person', to_field='user'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_info', to='rest_api.Person', to_field='user'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_info', to='rest_api.Person', to_field='user'),
        ),
    ]
