# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 13:20
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EduAdmin',
            fields=[
                ('creator', models.CharField(max_length=150, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('updater', models.CharField(max_length=150, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('creator', models.CharField(max_length=150, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('updater', models.CharField(max_length=150, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('caption', models.CharField(max_length=150)),
                ('introduction', models.TextField(max_length=1024)),
                ('number_student', models.IntegerField(default=0)),
                ('number_teacher', models.IntegerField(default=0)),
                ('number_admin', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rest_api.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('creator', models.CharField(max_length=150, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('updater', models.CharField(max_length=150, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=32)),
                ('grade', models.CharField(max_length=32)),
                ('class_in', models.CharField(max_length=128)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='rest_api.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('creator', models.CharField(max_length=150, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('updater', models.CharField(max_length=150, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('teacher_id', models.CharField(max_length=32)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='rest_api.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('creator', models.CharField(max_length=150, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('updater', models.CharField(max_length=150, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150, null=True)),
                ('sex', models.CharField(default='secret', max_length=8)),
                ('phone', models.CharField(max_length=16, null=True)),
                ('email', models.EmailField(max_length=128, null=True)),
                ('github', models.CharField(max_length=128, null=True)),
                ('qq', models.CharField(max_length=128, null=True)),
                ('weixin', models.CharField(max_length=128, null=True)),
                ('blog', models.CharField(max_length=128, null=True)),
                ('introduction', models.TextField(max_length=256)),
                ('is_staff', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(null=True)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('identities', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_identities', to='rest_api.UserProfile'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_identities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_identities', to='rest_api.UserProfile'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_identities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eduadmin',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edu_admins', to='rest_api.Organization'),
        ),
        migrations.AddField(
            model_name='eduadmin',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edu_admin_identities', to='rest_api.UserProfile'),
        ),
        migrations.AddField(
            model_name='eduadmin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edu_admin_identities', to=settings.AUTH_USER_MODEL),
        ),
    ]
