# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='introduction',
            field=models.TextField(max_length=256, null=True),
        ),
    ]
