# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20170326_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='number_organizations',
            field=models.IntegerField(default=0),
        ),
    ]
