# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 00:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_organization_number_organizations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='number_admin',
            new_name='number_admins',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='number_student',
            new_name='number_students',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='number_teacher',
            new_name='number_teachers',
        ),
    ]
