# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_auto_20170327_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='introduction',
            field=models.TextField(max_length=1024, null=True),
        ),
    ]
