# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_auto_20170327_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduadmin',
            name='email',
            field=models.EmailField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='eduadmin',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='eduadmin',
            name='phone',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='eduadmin',
            name='sex',
            field=models.CharField(default='secret', max_length=8),
        ),
    ]
